#!/usr/bin/env bash
# Script to install nginx and set some configuraiton options

apt-get -y update
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.html
service nginx start
