#!/usr/bin/env bash
# Script to install nginx and set some configuraiton options

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
