#!/usr/bin/env bash
# Script to install nginx and set some configuraiton options

apt-get -y update
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.youtube.com permanent;" /etc/nginx/sites-available/default
service nginx start
