#!/usr/bin/env bash
# Script to install nginx and set some configuraiton options

apt-get -y update
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.html
service nginx start
sed -i '/listen 80 default_server; rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx restart
