#!/usr/bin/env bash
# Script to install nginx and set some configuraiton options

apt-get -y update
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/404.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.youtube.com permanent;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
service nginx start
