#!/usr/bin/env bash
# Print nummbers to 20 with bad luck messages mixed in
c="bad luck from China"
j="bad luck from Japan"
i="bad luck from Italy"
x=1

while [ $x -le 20 ]
do
  case $x in

  4)
    echo "$x"
    echo "$c"
    ;;

  9)
    echo "$x"
    echo "$j"
    ;;

  17)
    echo "$x"
    echo "$i"
    ;;

  *)
    echo "$x"
    ;;

  esac
  ((x++))
done
